import {
  Text,
  Box,
  Flex,
  Stack,
  Heading,
  Image,
  VStack,
  Hide,
} from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Navbar from "../components/navbar";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const bg = "/homebg.png";
  return (
    <Box bgImage={bg}>
      <Head>
        <title>Utils</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        bg={"rgba( 0, 0, 0, 0.55 )"}
        boxShadow={"0 8px 32px 0 rgba( 31, 38, 135, 0.37 )"}
        backdropFilter={"blur( 10.5px )"}
        minHeight="100vh"
      >
        <Navbar />
        <Stack
          h={"100%"}
          p={5}
          maxW={"7xl"}
          mx={"auto"}
          color={"white"}
          mt={20}
        >
          <Flex
            h={"380px"}
            bg={"rgba( 0, 0, 0, 0.01 )"}
            boxShadow={"0 8px 32px 0 rgba( 31, 38, 135, 0.37 )"}
            backdropFilter={"blur( 10.5px )"}
          >
            <VStack
              w={{ base: "100%", lg: "50%" }}
              alignSelf={"center"}
              pl={"15px"}
            >
              <Text fontSize={"42px"} fontWeight={"bold"}>
                <span>GoGoGadgets</span> {""}
                is a place to interact with fun utilities
              </Text>
              <Text fontSize={"24px"} alignSelf={"self-start"}>
                A site for all the utilites you will need :)
              </Text>
            </VStack>
            <Hide below="md">
              <VStack alignSelf={"center"} w={{ base: "25%", lg: "50%" }}>
                <Image
                  h={{ md: "200px", lg: "220px" }}
                  objectFit={"contain"}
                  src="https://www.nicepng.com/png/full/870-8701139_your-logo-here-png-gloucester-road-tube-station.png"
                ></Image>
              </VStack>
            </Hide>
          </Flex>
        </Stack>
      </Box>
    </Box>
  );
};

export default Home;
